#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Smartass.Resource", IsApplication=true)]

namespace Smartass
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050003
			public const int glass_card_body_height = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int glass_card_footer_margin = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int glass_card_left_column_width = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int glass_card_margin = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int glass_card_two_column_margin = 2131034114;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add_image = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_launcher = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_start_new_game = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_stop = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_take_a_picture = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int monoandroidsplash = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090009
			public const int action_smartass_a_picture = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int action_stop = 2131296266;
			
			// aapt resource value: 0x7f090007
			public const int body_layout = 2131296263;
			
			// aapt resource value: 0x7f090004
			public const int footer = 2131296260;
			
			// aapt resource value: 0x7f090003
			public const int footer_container = 2131296259;
			
			// aapt resource value: 0x7f090006
			public const int layout = 2131296262;
			
			// aapt resource value: 0x7f090000
			public const int left_column = 2131296256;
			
			// aapt resource value: 0x7f090008
			public const int message = 2131296264;
			
			// aapt resource value: 0x7f090001
			public const int name = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int photo = 2131296258;
			
			// aapt resource value: 0x7f090005
			public const int timestamp = 2131296261;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int category_card = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int status_live_card_layout = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int menu_main = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public const int action_smartass_a_picture = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int action_stop = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int app_name = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int hello = 2131165186;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MenuTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Mono_Android_Theme_Splash = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int voice_trigger_start = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
